import { Container, Typography } from "@mui/material";


export default function Test() {
    return (      <div>
        <Container >
        <Typography variant="neonPink" align="center" fontSize={80}>WTFcinema</Typography>
        <Typography variant="body1" color="#ffffff">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.        
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        </Typography>
        <Container sx={{height: 60}}></Container>
        <Typography variant="body1" color="#ffffff">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Donec bibendum felis et felis facilisis, vel faucibus purus tempor. Curabitur at elit quis magna condimentum sagittis. Integer vehicula magna vel nulla vestibulum, eget auctor justo fermentum.        
        </Typography>
        </Container>
      </div>
)
}